### ISSUE TITLE
Использование базы данных Mysql

### ISSUE THREAD

**Issue by UUSR** [xinvestoriginal/NeiroNet-1.2#1]
@xinvestoriginal Уважаемый разработчик ,хотелось бы интегрировать в проект поддержку баз данных Mysql.

**Comment by xinvestoriginal** [comment]
встроить базы данных не сложно, но боюсь это усложнит код для понимания начинающим программистам, так что полноценный ИИ, если и буду выкладывать то в рамках другого проекта.

**Comment by UUSR** [comment]
@xinvestoriginal согласен ,код усложнять не нужно.
